### PR TITLE
Issue 2917

### PR DESCRIPTION
**Pull request by zhexu14**
This PR addresses Issue 2917 https://github.com/dcs-liberation/dcs_liberation/issues/2917 and allows CAS missions to be planned against airfields and FOBs

### CODE REVIEW

**Comment by DanAlbert** [comment]
I don't understand how this works as far as flight plan layout goes.

https://github.com/dcs-liberation/dcs_liberation/blob/674254e55bd570920e0a3d08d245effcae5fbb7b/game/ato/flightplans/cas.py#L81-L82

That's unchanged in this PR, so I'd assume any attempt to use this crashes.

With that question out of the way though.... how should flight plan layout work here? The patrol start/end points for this are probably very different than they are for a front line.

I wonder if the FR is perhaps being taken too literally, and this is better suited to being a different type of BAI?

@Starfire13, which properties of CAS that BAI doesn't fulfill are you aiming for? Area attack (to cover multiple garrisons), patrol (stay on station for a fixed time even if you can't find targets), or both?

**Comment by Starfire13** [comment]
> @Starfire13, which properties of CAS that BAI doesn't fulfill are you aiming for? Area attack (to cover multiple garrisons), patrol (stay on station for a fixed time even if you can't find targets), or both?

Here's an example of how I typically set it up manually. I find it works well. Essentially, I just want them to clear out any remaining stragglers within the zone that would prevent capture, after all the DEAD and BAI have done their thing.
Screenshot 2023-06-13 110638

For control point CAS, you wouldn't need a 20 mile radius search and engage range since you're not clearing stuff out of an entire frontline. 10 mile radius would be good enough.

Having this feature will actually be very useful in the Exercise Bright Star campaign I'm working on for Sinai, because there will be no more frontlines after the first base capture (so players can no longer plan a CAS over the frontline and drag the waypoints over). All capturing west of the Suez Canal is going to be via air assault only.

**Comment by DanAlbert** [comment]
Do you want that with or without a patrol though? It's not that we can't do the FR exactly as written, it just sounds like it may be one of those FRs that's trying to ask for the "simple" thing rather than something that's a better fit for the intent (and doing this isn't actually simple, because it forces us to make CAS do two things that have very little in common at the implementation level).

We probably do need to make this actually a new mission type (until my favorite https://github.com/dcs-liberation/dcs_liberation/issues/270 is fixed, any amount of variation in mission behavior is very error prone). What's not obvious to me yet is whether that mission type is:

1. Area attack BAI (with a better name): like sweep but for ground units. Fly the route, shoot what you see in the area, leave. Do not loiter.
2. Air assault CAS (also needs a better name): patrols the target area for the mission duration and attacks what it finds in the area. This is the FR as written, but with a different implementation.

**Comment by Starfire13** [comment]
No, there is no need to loiter. They can simply clear the circular search area and leave. They are only dealing with static defences after all.

**Comment by DanAlbert** [comment]
We should probably make a new mission type that's whatever the ground attack version of sweep is then. iirc there is a name for that but I can't remember it right now. It might just be a subclass of BAI?

**Comment by Starfire13** [comment]
This? https://www.merriam-webster.com/dictionary/armed%20reconnaissance

**Comment by DanAlbert** [comment]
Closing to clean up since a different approach is needed here.

**Pull request closed without merging**
