### PR TITLE
Migrate to PySide6.2.3

### PR DESCRIPTION
**Pull request by Raffson**
Turns out v6.2.3 is what we want, v6.2.2 works too but anything lower and pyinstaller starts complaining. Everything above v6.2.3 seems to cause problems with the map, for which I also had to change the order of loading and setting the page, i.e. in qt_ui/widgets/map/QLiberationMap.py the last two lines.

All that said this works fine on my end, though I'm still keeping this a draft until I've scanned all code in qt_ui for possible issues relating to the migration.

### CODE REVIEW

**Comment by Raffson** [comment]
Took a look at all warnings from PyCharm's inspector, couldn't find anything out of the ordinary 👍

**Comment by SnappyComebacks** [comment]
I received this error when trying to press `Accept Results`.  The window doesn't close at first press of  `Accept Results`, and pressing `Accept Results` a second time produces the following error:

```
2022-07-10 20:51:52,428 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 217, in process_debriefing
  File "qt_ui\simcontroller.py", line 91, in process_results
  File "game\sim\gameloop.py", line 75, in complete_with_results
  File "game\sim\missionsimulation.py", line 71, in process_results
RuntimeError: Simulation has no unit map. Results processing began before a mission was generated.
```

image

Edit:  Just checked `develop`, I don't get this error there.

**Comment by DanAlbert** [comment]
Why?

**Comment by Raffson** [comment]
@SnappyComebacks these are exactly the things I was expecting (also mentioned by CP in discord), I guess it's best to convert this back to draft or perhaps even close it for the time being, because it clearly needs more testing.

**Pull request closed without merging**
