### PR TITLE
Update most python dependencies

### PR DESCRIPTION
**Pull request by SnappyComebacks**
Updated most dependencies in requirements.txt
`starlette` couldn't be updated because `FastApi` depends on the current version.

Routes were changed to return `HTTP.OK` instead of `HTTP.NO_CONTENT` to mitigate the following error:

```
2022-07-10 12:13:03,661 :: uvicorn.error :: ERROR :: Exception in ASGI application
Traceback (most recent call last):
  File "g:\...\dcs_liberation\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "g:\...\dcs_liberation\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "g:\...\dcs_liberation\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\routing.py", line 68, in app
    await response(scope, receive, send)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\responses.py", line 162, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\exceptions.py", line 79, in sender
    await send(message)
  File "g:\...\dcs_liberation\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in _send
    await send(message)
  File "g:\...\dcs_liberation\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 533, in send
    raise RuntimeError("Response content longer than Content-Length")
RuntimeError: Response content longer than Content-Length
```

### CODE REVIEW

**Comment by SnappyComebacks** [comment]
Hm, I ran the deployed version and get this:
image

**Comment by Raffson** [comment]
You changed PySide2 to PySide6, that's probably why, ~~try changing the version only instead.~~

EDIT: PySide2 is up-to-date, migrating to PySide6 would require the alternative mentioned below

**Comment by Raffson** [comment]
Alternatively, you could also change all PySide2 imports to PySide6, but I believe @DanAlbert tried that not too long ago...

**Comment by SnappyComebacks** [comment]
You're right.  Its the imports, I'll I just assumed the build would catch them.  Not sure why it didn't.

**Comment by DanAlbert** [comment]
Last time I tried, pyside6 didn't work with pyinstaller.

**Comment by SnappyComebacks** [comment]
> Last time I tried, pyside6 didn't work with pyinstaller.

Am I further along then you were able to get last time?  (Should I continue to try to resolve these issues?)

**Comment by Raffson** [comment]
I'm also giving it a shot, from what I remember it's gonna be mainly fixing imports because some classes got reorganized within Qt.

**Comment by DanAlbert** [comment]
You can maybe dig up the log if my failures in discord. Iirc there's a bug filed against pyinstaller. It's not anything we were doing wrong, pyinstaller needs to take some extra steps to make pyside work, and the work for pyside6 is different than for pyside2.

Maybe that's changed by now. I had to rename all the imports from pyside2 to pyside6. That made everything _appear_ to work, but the application packaged by pyinstaller would not run, and there was no path forward.

My plan is to stick with pyside2 until we're off qt entirely.

**Comment by DanAlbert** [comment]
If not in the discord log, I may have left info in the revert? Check the log for requirements.txt. It might be in there.

**Comment by Raffson** [comment]
Yeah changing PySide2 to PySide6 is not enough, it's probably why the installer failed. As I mentioned there's a lot of stuff that got changed/reorganized. Some things are deprecated, meaning we have to rewrite some stuff here and there.

I got liberation to start up, but I'm missing the map completely. Step by step I think we'll get there...

**Comment by SnappyComebacks** [comment]
Ok I will revert out the PySide changes for now.  Here's Dan's prior attempt for anyone curious.  https://github.com/dcs-liberation/dcs_liberation/commit/2a75d14e0e9ba7ce3e58525adbddb90a29a210ee

**Comment by Raffson** [comment]
> Ok I will revert out the PySide changes for now.  Here's Dan's prior attempt for anyone curious.  https://github.com/dcs-liberation/dcs_liberation/commit/2a75d14e0e9ba7ce3e58525adbddb90a29a210ee

Awesome, I was just looking for that 😂

**Comment by SnappyComebacks** [comment]
Ok it's working again now.

**Pull request merged**
