### PR TITLE
Resolved #531

### LINKED ISSUE #531: OSError: invalid face handle
All releases from version 2.1.1 give me the ''OSError: invalid face handle error'' (sometimes a direct crash) on clicking the Take Off button. Version 2.1.0 and previous versions work fine.
Issue related with kneeboards?
Clean reinstallation of DCS doesn't solve the issue.

Capture

### PR DESCRIPTION
**Pull request by Hanninho**
Transfered my fix (https://github.com/Khopa/dcs_liberation/issues/531#issuecomment-808693439) into the code.

### CODE REVIEW

**Comment by DanAlbert** [comment]
Looks fine but am going to wait for someone that has seen the problem (not sure if you did, or if this is just a probable fix) before merging. lmk if I misunderstood.

**Comment by DanAlbert** [comment]
(wrong PR)

**Comment by Hanninho** [comment]
> Looks fine but am going to wait for someone that has seen the problem (not sure if you did, or if this is just a probable fix) before merging. lmk if I misunderstood.

Hi @DanAlbert,
yes, I had the error more or less permanently after the mission generation actually worked initially. I first reported the error in Discord (https://discord.com/channels/595702951800995872/595706079459934208/815337532287877171) and tried some solutions, but they didn't work, except for the current fix.
I tested the adjustment with the "naked", uncompiled code as well as with the compiled EXE and the error has not occurred at all.

**Comment by DanAlbert** [comment]
Great, thanks for confirming that. Merged.

**Pull request merged**
