### PR TITLE
Fix invalid squadron liveries

### PR DESCRIPTION
**Pull request by Raffson**
While messing with the livery scanner that I'm working on, I noticed a little typo for the 25th FS (A-10C II)

### CODE REVIEW

**Comment by Raffson** [comment]
~~I found more mismatches between livery names in the yaml files and DCS' livery names, @DanAlbert should I add them in this PR?~~

I got confused (again) between the ID (which is basically the path) and the name found in the description file. Sometimes they're the same, sometimes they're not. I have an idea to verify if there's more mismatches, will test it out and post the results...

**Comment by Raffson** [comment]
25th FS Osab AB, Korea (OS), "not found...", resources\squadrons\A-10C Warthog I\25th FS.yaml
VF-33 Starfighters 201, "not found...", resources\squadrons\F-14A 135-GR Tomcat (Late)\VF-33.yaml
VF-102 Diamondbacks 102 (2000), "not found...", resources\squadrons\F-14B Tomcat\VF-102.yaml
BP_RS01, "not found...", resources\squadrons\Mi-8\SAAF 253th Sqn.yaml
BP_RS01, "not found...", resources\squadrons\Mi-8\SAAF 255th Sqn.yaml
ERAF, "not found...", resources\squadrons\Mig-29\SAAF 697th Sqn.yaml
ERAF, "not found...", resources\squadrons\Mig-29\SAAF 699th Sqn.yaml
NAVY Standard, "not found...", resources\squadrons\S-3B\VS-35F.yaml

So yeah, 25th FS wasn't the only one...

**Comment by Raffson** [comment]
> 25th FS Osab AB, Korea (OS), "not found...", resources\squadrons\A-10C Warthog I\25th FS.yaml

Simple typo...
>VF-33 Starfighters 201, "not found...", resources\squadrons\F-14A 135-GR Tomcat (Late)\VF-33.yaml

Got renamed to `VF-33 Starfighters AB201 (1988)`
> VF-102 Diamondbacks 102 (2000), "not found...", resources\squadrons\F-14B Tomcat\VF-102.yaml

Got renamed to `VF-102 Diamondbacks 102`
> NAVY Standard, "not found...", resources\squadrons\S-3B\VS-35F.yaml
This is the livery name and not the ID, `usaf standard` is what it should be

> BP_RS01, "not found...", resources\squadrons\Mi-8\SAAF 253th Sqn.yaml
> BP_RS01, "not found...", resources\squadrons\Mi-8\SAAF 255th Sqn.yaml

These use a custom livery afaict, I have `Standard` in mind as a replacement

> ERAF, "not found...", resources\squadrons\Mig-29\SAAF 697th Sqn.yaml
> ERAF, "not found...", resources\squadrons\Mig-29\SAAF 699th Sqn.yaml

Another custom livery, but here I'm not so sure what I should use as a replacement. I did some research and it seems Syria does have Mig-29SM's with the ability to carry R-77's, however DCS doesn't reflect that, thus you can't use `SyAAF` because it's  only valid for Mig-29A. A workaround exists in copying (and a little editing) the livery and adding it as a custom livery for the S model, but somehow that doesn't feel right... Any suggestions?

**Comment by Starfire13** [comment]
I think rather than trying to figure out what is the best replacement for a custom livery, the default (for that country) should just be used. I don't particularly like the idea of custom liveries being used in the squadron files that get bundled with Liberation because there are a lot of folks who aren't going to have the right ones installed. The ones who do, and want to specifically use that livery, can now pick em using the livery selector.

**Comment by Raffson** [comment]
> I think rather than trying to figure out what is the best replacement for a custom livery, the default (for that country) should just be used.

Let me elaborate cause it seems like I haven't been clear enough regarding "DCS doesn't reflect that". I stumbled upon this issue while doing tests using the Golan Heights campaign. The opposing faction is Syria in this case but DCS doesn't allow Mig-29S' for Syria, only Mig-29As. So the work-around was using CJTF Red as country to allow the airframe. This also allows you to choose any livery that's available for the airframe. Here comes the annoying part, DCS only has a Syrian livery for the Mig-29A, so I can't use it to replace the squadron's livery as it expects a livery for the S model. Now I could just use SyAAF but then it would revert back to the default livery either way, which essentially doesn't change anything to the way things are, but anticipating for ED to add the Syrian livery to the S model. But tbh I don't like this solution too much either.

> I don't particularly like the idea of custom liveries being used in the squadron files that get bundled with Liberation because there are a lot of folks who aren't going to have the right ones installed. The ones who do, and want to specifically use that livery, can now pick em using the livery selector.

Totally agree with you there...

**Comment by Starfire13** [comment]
Ah I gotcha. In that case, it seems to me that it's better to just stick to some default MiG-29S livery that comes with DCS, and if someone wants a more realistic Syrian MiG-29S livery, they can go download one and use that. And someday if/when ED introduces an official Syrian livery for the MiG-29S, then we can switch to using that.

**Comment by Raffson** [comment]
Here's a list of all valid Mig-29S (original) liveries with their list of valid countries in DCS:

Air Force Standard {'RUS'}
Air Force Ukraine Standard {'UKR'}
Algerian AF FC-16 {'DZA'}
28 GvIAP_Andreapol {'RUS'}
Belarusian Air Force {'BLR'}
773 IAP_Damgarten {'RUS'}
426th Air Group_Erebuni {'RUS'}
KazAADF new (fictional) {'KAZ'}
KazAADF new (fictional digital) {'KAZ'}
KazAADF new faded (fictional) {'KAZ'}
KazAADF old (fictional) {'KAZ'}
Falcons of Russia {'RUS'}
1521th Air base_Mary-1 {'RUS'}
Strizhi {'RUS'}
Swifts {'RUS'}
115 GvIAP_Termez {'RUS'}
31 GvIAP_Zernograd {'RUS'}

None of these seem viable imo, except maybe for the Algerian livery, although I'm still on the fence about it. It's not like the Mi-8 where the "Standard" livery (mind that this is not the default, it's the ID, which corresponds with the folder-name) is more generic which could possibly be applied to any country. The alternative would be to simply change the squadron's airframe to Mig-29A, but that's something I favor even less.

So yeah, Algerian livery then? 🤣

**Comment by Raffson** [comment]
Actually, it has come to my attention that there's only squadrons for Mig-29S, and none for Mig-29A. In that case it seems reasonable to consider changing the airframe for the Syrian squadrons.

**Comment by Raffson** [comment]
Decided to go with the Algerian livery, may not be ideal but hopefully ED will release a Syrian livery for the S model in the future.

**Pull request closed without merging**
