### PR TITLE
F/A-18E/F Super Hornet AI Tanker mod v1.2 support

### PR DESCRIPTION
**Pull request by MetalStormGhost**
Added F/A-18E/F Super Hornet AI Tanker mod support (Chiller Juice Studios SuperBug Tanker AI version 1.2). Also added version information to the new game wizard for A-4E, JAS39 and UH-60L mods.

When/if the player-flyable Super Hornet mod support is also implemented, #1453 will be closed by that and this PR together.

### CODE REVIEW

**Comment by DanAlbert** [comment]
We're closing stale PRs. If this is still needed, please update and reopen.

**Comment by MetalStormGhost** [comment]
I checked the Chiller Juice Studios Discord and v1.2 is still the latest version of the Super Hornet Tanker mod. Reopening PR and requesting a review.

**Comment by MetalStormGhost** [comment]
I'll still update the changelog before requesting a review.

**Comment by DanAlbert** [comment]
Doesn't the exported data need to be verified with every DCS release? We have to do that with the not-modded aircraft in pydcs.

**Comment by MetalStormGhost** [comment]
> Doesn't the exported data need to be verified with every DCS release? We have to do that with the not-modded aircraft in pydcs.

Yes, if there have been changes to e.g. weapons which the modded aircraft use. For example, the AH-64D patch changed some of the 70mm Hydra rockets and ended up removing some of them, which had been used in some mods. RndName had to manually remove those from the 5.2.0 release of Liberation.

Most of the contents in the pydcs extensions stay the same across DCS updates. I always verify this by having the pydcs exports in a git repo and looking at the diffs with each update.

**Pull request closed without merging**
