### PR TITLE
Add Setting to hide enemy units in ME

### LINKED ISSUE #1570: Make all REDFOR units "hidden" in DCS Mission Editor by default
Due to the fact that I need to manually add the CTLD functionality and also manually change the carrier, tankers and AWACS radios and tacan frequencies, I need to open the mission miz file everytime before playing the mission.
That makes that I can see all REDFOR units and also I can see their attack plans, objectives.....

Hide1

It would be great if Liberation when generating the Miz file sets all REDFOR units as "Hidden".
This way people that need to edit or add some items to BLUEFOR does not need to see REDFOR plans or objectives.
In the other hand if a person really needs to edit something in REDFOR, this can be easly don in the mision editor just by activating the box "Show Hidden units"

Hide2

This optio would be highly welcomed by for those of us that need to edit the miz, but will keep the campaing Liberation still as surprise in the battlefield and this way is more exciting to play.
Thanks

### PR DESCRIPTION
**Pull request by RndName**
closes #1570

This adds a setting to hide all enemy units in the Mission Editor. Will be set to `Hide flights and front line` by default.

To show the enemy units in the Mission Editor, the User has to enable the "Show Hidden Units" Setting in the Mission Editor

grafik

### CODE REVIEW

**Comment by RndName** [comment]
I am unsure if this should hide all GroundObjects as well because we can still see them in the liberation UI all the time. Maybe this should only Hide Flights and Front line units as default.
Could be a dropdown Field with settings "Hide all, Hide Flights and Frontline, None"

**Comment by Hornet2041** [comment]
won't this affect things like the ability for F/A-18 and F-16 to see known, fixed position SAMs on their SA/HSD?

**Comment by RndName** [comment]
> won't this affect things like the ability for F/A-18 and F-16 to see known, fixed position SAMs on their SA/HSD?

There are 3 options:
- hidden on map
- hidden on planner
- hidden on mfd

I would assume (have not tested it so far) just hiding it on the map will not hide it on the mfd as there is a special setting

**Comment by RndName** [comment]
Okay i've tested it and the "Hidden on Map" is just not working correctly: https://forum.dcs.world/topic/252055-hidden-on-mfd-option/#comment-4914521
The only thing really working is Hidden on Planner but thats not the thing requested in the Issue as it will be still visible in the Mission Editor.
Making it Hidden on Map also overrides F10 visibility settings. So Fog of war will not work anymore for example.
As this is an DCS issue im going to close the PR

**Comment by SchmokedPancake** [comment]
Thanks for trying Rndname you have been pushing a lot of implantations and you are very appreciated

**Pull request closed without merging**
