### PR TITLE
Add Mi-24P Hind to DCS Liberation

### PR DESCRIPTION
**Pull request by UKayeF**

### CODE REVIEW

**Comment by jake-lewis** [comment]
Think this still needs a yaml entry e.g. resources/units/aircraft/Mi-24P.yaml 

Can basically copy the Hind-E, except the F entered service in '81 according to what I could find

**Comment by jake-lewis** [comment]
In fact you might as well just grab it from here :D https://github.com/jsjlewis96/dcs_liberation/commit/bf27f050944ffd95afd1832aa02570b8a9f499cd

**Comment by Khopa** [comment]
Hey, I think that's going to hard to merge this specific branch in develop since this was based on develop-3-x,. I see you're working on a new "hind" branch based on develop.

So i think we can close this PR, so you can open a new one : "hind"->"develop" ?


Edit : sorry, thought you were the same person @UKayeF & @jsjlewis96

**Review by Khopa — CHANGES_REQUESTED** [review]
See my comment in the PR thread.

**Comment by jake-lewis** [comment]
> Hey, I think that's going to hard to merge this specific branch in develop since this was based on develop-3-x,. I see you're working on a new "hind" branch based on develop.
> 
> So i think we can close this PR, so you can open a new one : "hind"->"develop" ?
> 
> Edit : sorry, thought you were the same person @UKayeF & @jsjlewis96

@UKayeF 90% sure this rebase has your changes & updates to yaml & factions, if you want to grab it go ahead https://github.com/jsjlewis96/dcs_liberation/tree/hind

**Comment by Khopa** [comment]
Well I'm going to import commits from both your branches into develop.
Namely the yaml and factions part from yours @jsjlewis96 as it's up to date with the newest develop. And the icons and other stuff from there.

**Comment by Khopa** [comment]
Closing because of difficulties merging your exact changes in develop.
I imported some of your commits that did not cause merge issue in develop branch.

**Pull request closed without merging**
