### PR TITLE
Fix default payloads for Mirage F1

### PR DESCRIPTION
**Pull request by Raffson**
Payloads are not showing up automatically, and thus the aircraft get generated without weapons. Apparently I missed the fact that the names of the payloads must exactly correspond with the mission type.

### CODE REVIEW

**Comment by Starfire13** [comment]
See https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-Loadouts

Having "Liberation" in the loadout name is not incorrect. For examples, see the loadout files for Viper, Hornet, Apache, etc.

**Comment by Raffson** [comment]
> See https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-Loadouts
> 
> 
> 
> Having "Liberation" in the loadout name is not incorrect. For examples, see the loadout files for Viper, Hornet, Apache, etc.

Could you verify if you can actually generate a mission with F1s that get armed correctly?

I was having trouble with the F-15D 'Baz' for exactly the same reason, so I tested the F1 to be sure and concluded that weapons aren't loaded properly...

**Comment by Starfire13** [comment]
Screenshot 2022-07-31 233450

Checked in mission editor and the loadouts are correct.

**Comment by Raffson** [comment]
Sorcery! 😂

Ok I'll convert this to draft meanwhile and try to figure out where the problem lies on my end...

**Comment by Raffson** [comment]
Well, I'm not sure what's going on here but it looks like it's more related to my save-file. I've got these weird things going on like the following:
image

But when I pass the turn, everything seems to sort itself out. Either way, I'm closing this PR as this is clearly not the correct fix...

**Comment by Starfire13** [comment]
Loadouts in DCS will override the loadouts in Liberation if they have the same name. So if your DCS loadouts are messed up somehow, that could be why.

**Comment by Raffson** [comment]
> Loadouts in DCS will override the loadouts in Liberation if they have the same name. So if your DCS loadouts are messed up somehow, that could be why.

I noticed some small subtleties like the following:

- `Liberation STRIKE` doesn't work, `Liberation Strike` does and `STRIKE` does too
- `Liberation CAP` doesn't work, it needs to be followed by `BARCAP`, `TARCAP`, `Fighter Sweep`, `Intercept` or `Escort`. However making one loadout `CAP` fills all of them.
- `Liberation ANTISHIP` doesn't work, `ANTISHIP` does. Not sure what works with `Liberation` in front of it
- etc...

So yeah, I think I got it more or less figured out. Clearly this is something to pay attention to.

**Comment by Starfire13** [comment]
> Not sure what works with Liberation in front of it

Wiki has the answer to that: "Name the loadout Liberation mission type, where mission type is the exact name of the mission type shown in the UI".

**Pull request closed without merging**
