### PR TITLE
Add a Github Action and Installer

### PR DESCRIPTION
**Pull request by parithon**
This PR seeks to add a continuous delivery option by automatically generating a release whenever a new tag is pushed to the repository. Additionally, because there is a dependency on the PyDCS/DCS repository I add that as a submodule instead of pulling it in as a pip package. Just add the **pydcs** folder to the PYTHONPATH environment variable and all works as expected.

- The Github Action will trigger whenever a new tag is pushed to the repository.
- The action will checkout the commit, prepare the python environment, build the binaries, generate an installer as part of the *build* pipeline.
- The action will then generate release notes from the changelog.md and create a new release named after the tag name as part of the *release* pipeline.
- If the tag contains anything other than a period or number it will be treated as a prerelease and create a pre-release instead.
- The final results will be a release with two assets, the original ZIP file and a new installer EXE file. Unfortunately because of windows' smart screen and other browser security measures the EXE might complain about the file.

Here is an example of the results from my forked repository:

image

> Add **pydcs** to the `PYTHONPATH` environment variable

image

Solves #95

### CODE REVIEW

**Comment by Khopa** [comment]
Thanks, this is great and this will help a lot ! Merging.

Just two questions, 

In Pycharm, i found no options to retrieve the git submodules automatically, so to make it work, i just cloned pydcs from command line. Do you know if there is a way to do it in Pycharm instead ? 

Also, i often make changes to pydcs myself on my fork, so i believe changing the repository location in .gitmodules will be enough to make github actions use my pydcs fork instead ?

**Comment by parithon** [comment]
Unfortunately I don't use PyCharm as my daily driver and know very little about the application. I know it will download any submodule automatically when you first clone the repository. However, it doesn't look like there is an option to initialize and update the submodule on an existing cloned repository; it requires you to manually do it via the Terminal.

Yes, if you change the location it will use your forked repo instead. Keep in mind that when you push that back to GitHub others will be targeting your forked version instead of the original repo too. Might cause some confusion if they made some changes to the original and never get those changes back into their liberation fork.

**Comment by emcek** [comment]
> In Pycharm, i found no options to retrieve the git submodules automatically, so to make it work, i just cloned pydcs from command line. Do you know if there is a way to do it in Pycharm instead ?

maybe here: https://www.jetbrains.com/help/pycharm/sync-with-a-remote-repository.html#update or https://www.jetbrains.com/help/pycharm/set-up-a-git-repository.html#clone-repo

Anyway I think you have to setup submodule by hand/git cli push to github and when you pull PyCharm shoul recognize it

**Comment by Khopa** [comment]
Yeah, i updated my Pycharm to the latest version and it seems to work much better. I was still using a 2018 version.

**Pull request merged**
