### PR TITLE
Notes to kneeboard

### PR DESCRIPTION
**Pull request by nosv1**
Implements https://github.com/dcs-liberation/dcs_liberation/issues/808

tbh, this probably isn't even needed anymore - or at least significantly less - so feel free to ignore but, again, quality learning experience 😎 

image
image
image

as for implementation, yeh little button in the toolbar, click it and it loads any currently saved notes in game.notes - i still couldn't bring myself to ignore the error checking and allow for AttributeError for old saves, so *it is compatible with old saves* 👀 

Only the SAVE button updates the game.notes - it's instant, but button sets text to SAVED for a couple of seconds before displaying SAVE again

Some improvements for future, if actually implemented, fancier editor, but that would involve more complex kneeboard page, generator prob, like ability to bold or underline and such

limitations, still kinda unfortunate can't hover or click anything while notes dialog is open, not sure how to get around that if it's even possible in this current state

question tho, where the heck does that '?' come from, i see it in the settings, stats and now this dialog, but you click it and shows a No Entry icon for your mouse and doesn't do anything afaik.

thanks for review and consideration <3

### CODE REVIEW

**Comment by bgreman** [comment]
To make the dialog modeless just remove the `setModal(true)`.  You're already calling `QDialog.show()` to display it, which is modeless by default.

To remove the help button, you can do the following in the `__init__()`, I believe:
`self.setWindowFlags(self.windowFlags() & not QtCore.Qt.WindowContextHelpButtonHint)`

However I think we can do this at the application level if _none_ of the help buttons on any of the dialogs do anything.

**Comment by nosv1** [comment]
ayee, so it's like a lot more useful now given can hover and stuff, ty and gg

submitted a separate pull request (https://github.com/dcs-liberation/dcs_liberation/pull/1382) for the removing of unused help buttons

**Comment by DanAlbert** [comment]
This seems like it should be per-flight rather than global? @Mustang-25 who asked for the feature, but that was my interpretation.

**Comment by Mustang-25** [comment]
per flight would definitely be nice and would allow you to add things like flight or package specific notes. But global still has its uses though like providing threat briefs or a theater wide comms ladder for MP groups.

**Comment by nosv1** [comment]
ah my bad, I'll get a per-flight implementation worked out. 👍 


the below commit is still just one page, hopefully, it was rebased correctly after the mess of last night 🙃

**Comment by bgreman** [comment]
Reopening after inadverent branch deletion

**Review by bgreman — APPROVED** [review]

**Pull request merged**
