### PR TITLE
Update db and new faction.py

### PR DESCRIPTION
**Pull request by ITAHawkmoon**
added some plane missing from the db

### CODE REVIEW

**Comment by Khopa** [comment]
Thanks. 👍  

The F-111 can not be added in the mission editor, hence why it was not in the db. It doesn't hurt though.
At least i think it can't ?

Merging.

Note : Please make your pull requests on the "develop" branch in the future, as the master branch is always a few hundred commits behind, which can lead to painful merges 😅

**Comment by ITAHawkmoon** [comment]
that's sad

**Comment by Khopa** [comment]
What do you mean ?

The new faction and F-111 in db have been added to the project since this PR has been merged.

**Comment by ITAHawkmoon** [comment]
misread sorry

**Pull request merged**
