### PR TITLE
Gripen mod support

### PR DESCRIPTION
**Pull request by bgreman**

### CODE REVIEW

**Comment by UKayeF** [comment]
Works out fine. Maybe add an extra faction (Sweden 2002 modded?) though that uses both the JAS39Gripen and the JAS39Gripen_AG. I don't have write access so I cannot merge it myself though.

**Comment by bgreman** [comment]
> Works out fine. Maybe add an extra faction (Sweden 2002 modded?) though that uses both the JAS39Gripen and the JAS39Gripen_AG. I don't have write access so I cannot merge it myself though.

Extra faction added and prices somewhat reduced based on player feedback.

**Comment by UKayeF** [comment]
To be fair the Gripen (AG) is way too cheap for what it does, especially in the SEAD role. Main reason for that is the Mar-1 missile which seems very overpowered. I don't know if it will get fixed but I've had it hit an SA-10 from 58nm distance while hitting speeds in excess of Mach 10. Nothing the SA-10 or the SA-15 sites surrounding it could do against that.

**Comment by bgreman** [comment]
> To be fair the Gripen (AG) is way too cheap for what it does, especially in the SEAD role. Main reason for that is the Mar-1 missile which seems very overpowered. I don't know if it will get fixed but I've had it hit an SA-10 from 58nm distance while hitting speeds in excess of Mach 10. Nothing the SA-10 or the SA-15 sites surrounding it could do against that.

Do you have suggestions for pricing?  I'm basically trying to go by existing airframes, and originally priced both at 30M to bridge the gap between the Hornet/Tomcat and the F22.  I didn't realize the MAR-1 was so broken, definitely seems like I should at least bump the AG back up to 26 to match the AA.

It does look like someone reported the MAR-1 speed issue https://github.com/whisky-actual/Community-JAS-39-C/issues/42

**Pull request merged**
