### PR TITLE
Add guard for squadron

### LINKED ISSUE #2323: 'NoneType' object has no attribute 'location'
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2652273486

### Description

If you try to plan a flight on turn 0, you get this error.

Screenshot 2022-07-16 145257

In 5.2, the Create Flight window still pops up, but just shows you have no capable aircraft available.

Screenshot 2022-07-16 145311

If you've got flights planned and hit take off, and then abort and try to plan another flight, you get the same error. This is with fast forward turned off.

### Save game and other files

This save is on turn 0 with no aircraft. Try planning a package and you'll get the error.
[No Aircraft Turn 0 Save #4101.zip](https://github.com/dcs-liberation/dcs_liberation/files/9125187/No.Aircraft.Turn.0.Save.4101.zip)

For this save, hit take off, then abort, then try to plan a package. You'll get the error.
[8 Aircraft Turn 1 Save #4101.zip](https://github.com/dcs-liberation/dcs_liberation/files/9125190/8.Aircraft.Turn.1.Save.4101.zip)

### PR DESCRIPTION
**Pull request by Raffson**
Fix #2323 

This was an error on my part when fixing a bug w.r.t. OffMapSpawn bases being able to select the start-type.

### CODE REVIEW

**Comment by DanAlbert** [comment]
Why does the start type selector care about the squadron?

**Comment by Raffson** [comment]
> Why does the start type selector care about the squadron?

https://github.com/dcs-liberation/dcs_liberation/pull/2252

**Comment by DanAlbert** [comment]
It's not obvious, so it needs a comment.

**Comment by Raffson** [comment]
> It's not obvious, so it needs a comment.

Would you want aircraft to start cold when they spawn "OffMap"?

**Comment by DanAlbert** [comment]
That's not the part that's changing. Why does it matter if there's no squadron selected?

**Comment by Raffson** [comment]
> That's not the part that's changing. Why does it matter if there's no squadron selected?

That's not even the point... if squadron is None, executing `squadron.location` will raise an exception... how is that not obvious?

**Comment by Raffson** [comment]
And FYI, when an `AND` expression is evaluated, if the first part fails, the second won't get executed, so my fix is "safe".

**Comment by DanAlbert** [comment]
Had misread and didn't see the squadron reference (I'll blame horizontal scrolling because I'm ony phone, but probably just brain dead).

**Comment by Raffson** [comment]
> Had misread and didn't see the squadron reference (I'll blame horizontal scrolling because I'm ony phone, but probably just brain dead).

That explains a lot 😂

**Pull request merged**
