### PR TITLE
Add Vanilla theme icons for weather conditions

### PR DESCRIPTION
**Pull request by renj-ek**
Fix for Issue [#1062](https://github.com/dcs-liberation/dcs_liberation/issues/1062)

Adding in vanilla theme icons for all weather conditions and times of day
Updated uiconstants.py to use the icons from the users selected theme.

Fix the barely visible text in the Intel Box

dcs_theme

vanilla_theme

### CODE REVIEW

**Comment by DanAlbert** [comment]
LGTM, thanks!

Out of curiosity, are you fixing this because you actually use that theme, or just because it was tagged with "good first issue"? I think the last time we'd discussed it we had decided to just remove the theme because as far as any of us can tell no one uses it (and most people don't know it exists at all), it just hadn't been enough of a bother to deal with removing either :)

**Comment by renj-ek** [comment]
Sorry about the extra third commit. I was going to create a separate issue but realised Issue #1062 mentions the barely visible text, so I was able to include it here.

**Comment by renj-ek** [comment]
> LGTM, thanks!
> 
> Out of curiosity, are you fixing this because you actually use that theme, or just because it was tagged with "good first issue"? I think the last time we'd discussed it we had decided to just remove the theme because as far as any of us can tell no one uses it (and most people don't know it exists at all), it just hadn't been enough of a bother to deal with removing either :)

I'm a new developer and was looking for good first issues. I also play DCS and about to start doing some liberation.

I personally wouldn't use this theme haha.

**Comment by DanAlbert** [comment]
If you @ ColonelPanic in our discord I'll get you added to the dev channel.

**Comment by Starfire13** [comment]
I actually prefer the font style and size on the Vanilla theme over the default, but I don't use it because the white is a tad glaring.

**Pull request merged**
