### PR TITLE
Fix end-combat

### LINKED ISSUE #2253: Not all map features updating properly
### Affected versions

Development build

### Development build

_No response_

### Description

I found that many functions on the map are not updating properly. Things like the `ThreatZones` and `NavMeshes` in the left menu only update once, after that it seems to be getting the same data over and over again. Options on right side like "Ships", "Factories", "Air defences", etc. seem to be FUBAR as well. Also supply routes were not being drawn in the correct color after a capture event. So yeah, I think I found a new issues to solve 🤣 

An overview:

- [x] ThreatZones not updating after first update
- [x] Navmeshes not updating after first update
- [x] SupplyRoutes not updating at all
- [x] Air defences: FUBAR
- [x] Factories: FUBAR
- [x] Ships : FUBAR
- [x] Other ground objects: FUBAR
- [x] Active combat: doesn't remove lines when combat ends (dead units should be erased after some period?)
- [x] Allied/Enemy IADS network: doesn't seem to do anything, using some debug messages I can see connections that are linked with themselves

### Save game and other files

Any campaign should do since it's mostly front-end stuff...

### PR DESCRIPTION
**Pull request by Raffson**
The main reason why combat lines stay drawn on the map. Though in my test I noticed 2 exceptions, not python errors just to be clear, i.e. 2 combat lines stayed active for units that were dead. The special case was the fact that they were both located right on top of the airbase icon. Not sure why this is happening and if I had to guess, it's a problem that's separate from this one.

### CODE REVIEW

**Comment by Raffson** [comment]
Partial fix #2253

**Review by DanAlbert — COMMENTED** [review]
But why?

**Comment by Raffson** [comment]
> But why?

Wdym why?

**Comment by DanAlbert** [comment]
> > But why?
> 
> Wdym why?

What does this PR accomplish?

**Comment by Raffson** [comment]
> What does this PR accomplish?

At the time I noticed combat lines that stayed drawn after combat has ended. Just to confirm I did another test, and to my surprise lines disappear as they should, without the change in this PR of course. So I think it'd be wise to investigate this a little further, but imo this should still be merged simply because it reflects consistency across all other update events. It's literally the only update event that sticks out by not returning itself.

**Comment by DanAlbert** [comment]
> > What does this PR accomplish?
> 
> At the time I noticed combat lines that stayed drawn after combat has ended. Just to confirm I did another test, and to my surprise lines disappear as they should, without the change in this PR of course. So I think it'd be wise to investigate this a little further, but imo this should still be merged simply because it reflects consistency across all other update events. It's literally the only update event that sticks out by not returning itself.

I'm fine with merging this for consistency with the other APIs, but the PR description was extremely misleading, because there is certainly zero behavioral difference.

**Pull request merged**
