### PR TITLE
Allocate per-flight radio channels, set up preset channels.

### PR DESCRIPTION
**Pull request by DanAlbert**
Add central registries for allocating TACAN/radio channels to the
Operation. These ensure that each channel is allocated uniquely, and
removes the caller's need to think about which frequency to use.

The registry allocates frequencies based on the radio it is given,
which ensures that the allocated frequency will be compatible with the
radio that needs it. A mapping from aircraft to the radio used by that
aircraft for intra-flight comms (i.e. the F-16 uses the AN/ARC-222)
exists for creating infra-flight channels appropriate for the
aircraft. Inter-flight channels are allocated by a generic UHF radio.

I've moved the inter-flight radio channels from the VHF to UHF range,
since that's the most easily allocated band, and inter-flight will be
in the highest demand.

Intra-flight radios are now generally not shared. For aircraft where
the radio type is not known we will still fall back to the shared
channel, but that will stop being the case as we gain more data.

Tankers have been moved to the Y TACAN band. Not completely needed,
but seems typical for most missions and deconflicts the tankers from
any unknown airfields (which always use the X band in DCS).

Fixes https://github.com/Khopa/dcs_liberation/issues/108

### CODE REVIEW

**Comment by DanAlbert** [comment]
[Better radio channels support.](https://trello.com/c/pmKlMnMw/105-better-radio-channels-support)

**Comment by Khopa** [comment]
This is amazing, it makes it so much easier to use the radio with the F/A-18C !
Great job again 👍 

I also understand that COMMS channel setup is only supported for the F-16C and F/A-18C for now, so i'll create tasks on trello to support other aircrafts with COMM channels support if that's fine with you.

I also noticed an error on mission generation; this will happen with new save files that have a carrier, since briefinggen.py still use the old tacan properties stored in ControlPoint objects that you removed, see : 

```
Traceback (most recent call last):
  File "D:\Work\dcs_liberation\qt_ui\windows\mission\QMissionPlanning.py", line 156, in on_start
    self.game.initiate_event(self.gameEvent)
  File "D:\Work\dcs_liberation\game\game.py", line 178, in initiate_event
    event.generate()
  File "D:\Work\dcs_liberation\game\event\event.py", line 111, in generate
    self.operation.generate()
  File "D:\Work\dcs_liberation\game\operation\frontlineattack.py", line 41, in generate
    super(FrontlineAttackOperation, self).generate()
  File "D:\Work\dcs_liberation\game\operation\operation.py", line 286, in generate
    self.briefinggen.generate()
  File "D:\Work\dcs_liberation\gen\briefinggen.py", line 103, in generate
    self.description += str(cp.tacanN)
AttributeError: 'ControlPoint' object has no attribute 'tacanN'
```

**Comment by DanAlbert** [comment]
Ah, good catch. Thought I'd cleaned up all the users. Will get that fixed.

**Comment by DanAlbert** [comment]
Okay, briefing is fixed. Sorry about that, thanks for catching it! I did remove one thing from the briefing while doing that was the `nav_target_info` that we get from pydcs. It doesn't appear to contain any interesting information. The bottom part of the player's section of the briefing would just say something like:

```
PP1
PP2
PP3
PP4
```

for the JF-17, or even just simply `ST` for the F-14 (no other aircraft affected). I'm hoping to add more useful target information to the kneeboard/briefing next, so will expand that to something more useful then if that's okay.

**Comment by DanAlbert** [comment]
Also, any thoughts on a list of most used aircraft to prioritize for fleshing out radio info? I'm guessing:

* F-14
* M-2000
* AV-8B
* JF-17
* AJS37

All the FC3 aircraft I think are trivially mapped to the whole spectrum, since they don't really have control over their individual radios.

**Comment by Khopa** [comment]
Yep, we should probably add these one first. 

I also have an open issue for Mig-15,19 and 21 radios being unable to dial the frequency given in briefing.
Also the warbirds can be pretty tedious regarding radio frequencies.

For now i'm merging this in develop, i'll try to do the M-2000C first if that is fine with you.

Thanks again ! 👍

**Comment by DanAlbert** [comment]
Yeah, those should be easy to fix now. The only trouble will be finding the info for planes neither of us owns, but we can probably find someone that can help with those.

**Pull request merged**
