### PR TITLE
Added support for VSN F-4B/C mod.

### PR DESCRIPTION
**Pull request by Nosajthedevil**
Added support for VSN F-4B/C mod.

Added Aim-9J, Aim-9Juli, and Aim-7P to weapons files - altering fallbacks to other weapons as necessary.

Removed the KH-28 and altered necessary fallbacks since ED removed the missile.

Updated factions: USA 1975 to include F-4B/C and A-4; USN 1985 to include the 4B instead of the 4E; USA 1965 to include F-4B/C and Forrestal - note would rather use something less capable than the Perry as an escort to represent the late 60s - will revisit once I understand how to allow Frigates into carrier group. Was looking at possibly using a leander as a substitute but I could only get it to work by changing from frigate to destroyer in resource unit yaml.

### CODE REVIEW

**Comment by Nosajthedevil** [comment]
Sorry - should have squashed these, didn't realize it (or know what that was) until after I had committed to my fork and then couldn't figure out how to revert.

**Comment by DanAlbert** [comment]
There's a lot going on in this PR and I'm struggling to figure out which parts are actually part of the F-4 mod and which aren't. In the future, please try to keep PRs focused. Mega PRs are *much* harder to review (I've been looking at this for half an hour and still don't know what's going on).

> Added Aim-9J, Aim-9Juli, and Aim-7P to weapons files - altering fallbacks to other weapons as necessary.

Those weapons are added by this mod, right? If so, I'm not actually sure how this will behave. I'll need to investigate if that will break anything for people that do not have this mod before this can be merged (it could be a while, so if you want to land the rest of the mod without that, remove that part of the PR).

**Comment by Nosajthedevil** [comment]
Understood, I probably should have split this up into two or three PRs - one for the f-4 and one or two for the weapons, most of which were added by ED and not the mod. I tried to summarize below, if it doesn't make sense I'll just split this up into multiple PRs sometime this week.

Aim-7P was added by ED last year for the F-14, F/A-18, F-15C and I think the F-15E. It isn't related to or used by the F-4 mod. It IOC'd in 1992 and is an update to the Aim-7MH. I have the AIM-120B falling back to the 7P ( was previously falling back to the MH), the 7P falling back to the MH, and I moved the MH date to 1987 so it would sit at a midpoint between the 7M and the 7P but I can't find any firm data that that's the correct date. It falls back correctly for me, I've been using those files for a month or two. Not saying you should take my word for it of course - there could be something I'm missing.

The Aim-9J and the Aim-9Juli were added by ED for the Mirage F-1 although the F-4 mod uses them. The F-4 mod added a 2x9j and 2x9Juli. I didn't have any problems falling back through them to the -B for either the F-4 or the A-4, however I did not test with the mirage yet. Didn't think to until just now... I imagine the F-4E module will also use them whenever it is released.

One thought I just has is that currently I have the earlier Aim-9s falling back 9L to 9P5 to 9P to 9Juli to 9J to 9B, but since the 9Juli is an L seeker head on a J body and the L seeker is better than the 9P5s seeker, I wonder if the 9Juli should actually be moved up between the 9L and 9P5.

Also, I removed the KH-28 ARM since ED removed it from the SU-17's inventory.

**Comment by DanAlbert** [comment]
> I'll just split this up into multiple PRs sometime this week.

That needs to happen regardless (we want to keep commit history readable because that makes releases easier to manage). I can also do it for you now that I know what belongs where, it just won't be today :)

**Comment by Nosajthedevil** [comment]
I'll do it. I need to learn how anyway.

**Comment by Nosajthedevil** [comment]
Closing to split up into smaller PRs

**Comment by DanAlbert** [comment]
Sounds good. lmk if you have questions about how. I don't use the github desktop app (but I'm guessing you do) so I'm not sure how much help I'll be, but I can try :)

**Pull request closed without merging**
