### PR TITLE
Made separate russia 1975 for hind-f

### PR DESCRIPTION
**Pull request by jake-lewis**
Technically not in service in 75, but realised the Mig-29A wouldn't be either, hence "prototype". Might not be worth the faction clutter in this case. 

Did get me thinking that mayeb there should be an option for an airframe to be "player only" in a faction, so that we can fly it, but the AI won't buy/use it themselves?

### CODE REVIEW

**Comment by DanAlbert** [comment]
> Did get me thinking that mayeb there should be an option for an airframe to be "player only" in a faction, so that we can fly it, but the AI won't buy/use it themselves?

Idk how this would be done without making a pile of bugs. It's a lot of places to add special cases in the UI, procurement, aircraft allocation, etc. What did you have in mind?

**Comment by DanAlbert** [comment]
As far as the actual change goes, any reason to keep both types of Hind? Idk my Russian aircraft.

**Comment by jake-lewis** [comment]
> As far as the actual change goes, any reason to keep both types of Hind? Idk my Russian aircraft.

Hind-E is the closest to the year at 76, the F was 82. The only real difference is mg -> cannon, and the fact that it's playable, so maybe not worth keeping the old one depending on how people feel about historical accuracy

**Comment by jake-lewis** [comment]
> > Did get me thinking that mayeb there should be an option for an airframe to be "player only" in a faction, so that we can fly it, but the AI won't buy/use it themselves?
> 
> Idk how this would be done without making a pile of bugs. It's a lot of places to add special cases in the UI, procurement, aircraft allocation, etc. What did you have in mind?

hadn't thought about it properly, that _does_ seem like a pain, probs not worth it

**Comment by DanAlbert** [comment]
> > As far as the actual change goes, any reason to keep both types of Hind? Idk my Russian aircraft.
> 
> Hind-E is the closest to the year at 76, the F was 82. The only real difference is mg -> cannon, and the fact that it's playable, so maybe not worth keeping the old one depending on how people feel about historical accuracy

I suspect anyone picking this faction is picking it specifically to use the flyable hind, so might as well remove the unflyable one?

**Pull request merged**
