### PR TITLE
Added option for only night missions

### LINKED ISSUE #1786: Night only missions
Since we have day only missions option, it would be nice to include an option for night only missions.

### PR DESCRIPTION
**Pull request by MetalStormGhost**
Added option for only night missions. Resolves #1786

### CODE REVIEW

**Comment by magwo** [comment]
Doesn’t this make it so that you can select both night only and day only, at the same time. Wouldn’t it make more sense to make this into an enum and a select?

**Comment by MetalStormGhost** [comment]
Yes, it does. Currently day only is prioritized when both are selected. I can change it to an enum and a combobox/drop-down menu, but I fear that will break save compatibility.

**Comment by Starfire13** [comment]
I feel that breaking save compatiility is a very short term issue (folks can simply delay updating for a few days till they move on to their next campaign). In the long term, having the UI follow the principle of least astonishment is the better choice. Having both day and night selectable is more confusing so you'd either have to provide the information that day overrides night or the user would have to look this up/ask on Discord/test it to understand it. So, I agree that going with an enum and dropdown menu is the most logical (and most easily understandable) way to go.

**Comment by SnappyComebacks** [comment]
> but I fear that will break save compatibility.

You are targeting this branch for `develop`.  It's always OK to break save compatibility on `develop`.  (And it's already been broken from 5.x.x anyways.)

**Comment by magwo** [comment]
Looks good to me! Have you tested that the setting gets saved and loaded correctly from the campaign file?

**Comment by MetalStormGhost** [comment]
Yes I have, it gets saved and loaded from the .liberation file.

**Review by magwo — APPROVED** [review]

**Comment by magwo** [comment]
Nice work. Looking forward to playing with this setting. Night missions are awesome.

**Comment by DanAlbert** [comment]
What do "no night missions" and "no day missions" mean when there are no turns?

**Comment by magwo** [comment]
> What do "no night missions" and "no day missions" mean when there are no turns?

Good point. Unsupportable? So we should just remove all this night/day mission code?

Or, we could actually skip directly from, for example, 06:00 to 18:00 if night missions only is selected. And skip from 18:00 to 06:00 if day only missions is selected.

Technically possible, not sure if it makes sense though.

**Comment by magwo** [comment]
> What do "no night missions" and "no day missions" mean when there are no turns?

Good point. Unsupportable? So we should just remove all this night/day mission code?

Or, we could actually skip directly from, for example, 06:00 to 18:00 if night missions only is selected. And skip from 18:00 to 06:00 if day only missions is selected.

Technically possible, not sure if it makes sense though.

**Comment by magwo** [comment]
> What do "no night missions" and "no day missions" mean when there are no turns?

Good point. Unsupportable? So we should just remove all this night/day mission code?

Or, we could actually skip directly from, for example, 06:00 to 18:00 if night missions only is selected. And skip from 18:00 to 06:00 if day only missions is selected.

Technically possible, not sure if it makes sense though.

**Comment by magwo** [comment]
> What do "no night missions" and "no day missions" mean when there are no turns?

Good point. Unsupportable? So we should just remove all this night/day mission code?

Or, we could actually skip directly from, for example, 06:00 to 18:00 if night missions only is selected. And skip from 18:00 to 06:00 if day only missions is selected.

Technically possible, not sure if it makes sense though.

**Comment by Starfire13** [comment]
We would still need some sort of time skip (be it automatic or manual) anyway since not all aircraft are capable of night time missions. Most of the WW2 aircraft, for example.

**Comment by DanAlbert** [comment]
That's what the fast forward button does.

**Comment by Starfire13** [comment]
Fast forward only fast forwards till first contact.

**Comment by DanAlbert** [comment]
That's true right now, I'm talking about after turns are gone.

**Comment by DanAlbert** [comment]
I haven't reviewed because my question above still hasn't been answered.

**Comment by MetalStormGhost** [comment]
I feel like the question what to do after turns are gone falls a little outside the scope of this PR, but I'm good with @magwo 's suggestion. Until then, merging this option would enable it to make into the 5.1.0 release.

**Comment by DanAlbert** [comment]
It's out of scope for this PR sure but it's most likely that 6.0 will not have turns so it serves no purpose in this branch. You avoid day missions by not planning player missions in the day and just fast forwarding until night. If it's not going to serve any purpose in 6.0, there's no reason to merge it to 6.0.

If for whatever reason that doesn't happen in 6.0 we can merge it then, but I don't see a point to merging a feature that we plan to remove before it ever ships.

I should also mention that the "no night missions" option doesn't work, and so this won't either. DCS models seasons. The sunset/sunrise time is different every day, and we don't account for that.

**Comment by DanAlbert** [comment]
(aside from the last point, I think this is one of those rare cases where the PR should go to a branch other than develop, but idk if it's worth expanding a broken feature)

**Comment by RndName** [comment]
Merged to 5.1 with d2eb98bc
Had to clear circular dependencies first

**Pull request closed without merging**
