### PR TITLE
Fix dead carriers

### LINKED ISSUE #2405: Carrier killed in state.json but not being removed from game
### Affected versions

Development build

### Development build

4211

### Description

Carrier refuses to die. I believe it is a zombie carrier and is out to infect us all with SU-33 infection bullets! Watch out!

Lmao, in all seriousness though Star helped me confirm that it wasn't one sided

### Save game and other files

[Beta.zip](https://github.com/dcs-liberation/dcs_liberation/files/9481676/Beta.zip)

### PR DESCRIPTION
**Pull request by RndName**
Reopen #2435 as i am not able to push commits to this pr

@MetalStormGhost With V6 i reworked the ground object handling completly and adopted all other generators but must have missed the carrier generator.  Before the rework units were removed from the units list of a group and therefore would not be generated. Now we use the alive flag for that instead of removing them from the list.

I fixed a small bug in the PR but otherwise it looks good. Thanks!

### CODE REVIEW

**Comment by RndName** [comment]
@DanAlbert Ive reviewed & tested the code and it works as expected but there is one issue i found while testing killing enemy carriers:

When you kill an enemy Carrier the Autoplanner is not able to handle it any more. In the screenshot (Marianas campaign) you can see the result after submitting and skipping 2 turns. Seems that the ai is not buying anything else.
grafik

Actually thats not an issue of this PR at all but i just wanted to mention it

**Comment by DanAlbert** [comment]
> When you kill an enemy Carrier the Autoplanner is not able to handle it any more.

Not able to handle what? Is Shandong the carrier?

**Review by DanAlbert — APPROVED** [review]

**Comment by RndName** [comment]
> Not able to handle what? Is Shandong the carrier?

Yes Shandong is the Carrier which was destroyed. With unable to handle i mean the Autoplanner will not buy Aircraft anywhere else. All the Aircraft at the carrier are unavailable because the runway is destroyed but can not be repaired.
Dont know if it could be possible to transfer the Squadrons or how the logic of the planner can be set to take this into account.

As i said not part of this PR and a thing which was there before that change. So for this PR its ready to be merged :)

**Comment by Starfire13** [comment]
It's probably quite realistic that squadrons on a sinking carrier don't get to transfer off. The priority would be to get personnel to the lifeboats, rather than going through the complex task of getting all the aircraft fuelled and brought up to the flight deck (if the elevators even still work) and launched.

**Comment by RndName** [comment]
My point is not about transfer. The autoplanner will not buy aircraft at different bases. Nvm different issue

**Pull request merged**
