### PR TITLE
Starfire's loadouts for DCS World 2.7.9.17830 open beta.

### LINKED ISSUE #1836: F-16 ECM pod support for next release
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The F-16 ECM pod will be released in the next Open Beta. In case an interim release is made before 6.0.0, the F-16 ECM pod should be included.

**Additional context**
image
https://www.digitalcombatsimulator.com/en/news/newsletters/345a4089f1222f5f84a152683a2c1544/

### PR DESCRIPTION
**Pull request by MetalStormGhost**
@Starfire13 's loadouts for DCS World 2.7.9.17830 open beta.

I opened a pull request for this to discuss whether we should ship Starfire's loadouts with Liberation. I had meant to do this earlier already and now seemed like a good time with DCS 2.7.9.17830 release and the Mosquito's rockets.

Resolves #1836 if cherry-picked for the 5.1.x release.

Starfire — 2021-12-24 at 12:28
New loadout pack. I completely redid my Viper loadouts (and ECM pod is now included for all A2G loadouts), added the new rockets to the Mossie, and there are also some improvements to the Hornet and Hog loadouts.
https://discord.com/channels/595702951800995872/768556702068113449/923884847284510731

### CODE REVIEW

**Comment by DanAlbert** [comment]
Some of these (viper and hornet) are things I already maintain. I'll have a look but I'm guessing those get dropped.

**Comment by DanAlbert** [comment]
At a glance these are also way more difficult to maintain. Liberation knows to fall back to other loadouts to fill missing loadouts. OCA/Aircraft, BAI, and CAS are basically all the same loadouts (idk what I'd make different between those for the viper). Defining all three explicitly just triples the workload to modify that loadout for no benefit.

**Comment by MetalStormGhost** [comment]
> Some of these (viper and hornet) are things I already maintain. I'll have a look but I'm guessing those get dropped.

I can revert those to the previous versions. @Starfire13 any comments on the OCA, BAI & CAS loadouts above?

@DanAlbert what's your take on including e.g. these warbird loadouts with Liberation releases?

**Comment by DanAlbert** [comment]
I don't care at all about the WWII stuff, so have at it.

These are more or less impossible to review. Can we get a summary of what was changed?

**Comment by Starfire13** [comment]
@MetalStormGhost I am fine with you making any modifications to any of the loadouts, as I my own loadouts will always override any differences anyway on my end. I specifically set out to create unique loadouts for each mission type because it gives me a quick way to swap a loadout if I wish to use a different one for a specific target (e.g. I might pick a DEAD loadout for a specific BAI flight if I think the DEAD loadout makes more sense against that specific target). However, the loadouts I make still have to work well even if no modifications are made (e.g. my OCA/Runway loadouts won't have guided bombs because the AI can't use those, even though I myself always switch to a loadout with guided bombs when I fly OCA/Runway).

As an example of why my loadouts vary, both my CAS and DEAD Viper loadouts have Mavericks. But the CAS loadout carries double-racked D-variant Mavs for anti-armour, while my DEAD loadout carries the G-variant that has nearly twice the range and has a penetrating blast fragmentation warhead. The trade off is that the Viper can only carry a single G-variant Mav per pylon, but having more limited ordnance is less of an issue for DEAD compared to CAS where you would potentially have way more targets. The extra range on the other hand, is much more useful for DEAD.

**Comment by DanAlbert** [comment]
Does using mavericks for DEAD not just result in a ton of dead AI pilots and no dead SAMs? I'm worried that your loadouts only work well for "I plan all my own missions".

**Comment by Starfire13** [comment]
Yeah, DEAD is a tough one for Vipers cos they are kinda limited to what they can use for DEAD. With Hornets I have good stand off options like the SLAM-ER, or JSOW-C. With Vipers, it feels like the Mav-G is their longest range option apart from the JSOW-A , which doesn't reliably kill SAMs because it's so weak. What would you suggest as an alternative?

**Comment by DanAlbert** [comment]
The way they're already configured: the JSOW-A. The weapon might have a lower chance of a T-kill but the maverick has an extremely low change of ever being in range against everything but the SA-6 and SA-3, so that doesn't seem worth it at all. The JSOW at least keeps them far enough away to maximize survival chance.

**Comment by Starfire13** [comment]
Fair enough. Here's the Viper loadout modified to use the JSOW-A for DEAD. I opted for a single JSOW-A per pylon as I think double-racking them is too heavy for the AI to handle and they'd just be in afterburner the whole way.

[F-16C_50.zip](https://github.com/dcs-liberation/dcs_liberation/files/7775700/F-16C_50.zip)

**Comment by MetalStormGhost** [comment]
Closing this PR since it's replaced by #1872

**Pull request closed without merging**
