### PR TITLE
Iads fix

### LINKED ISSUE #2537: IADS Network error caused by dead groups
### Affected versions

Development build

### Build information

_No response_

### Description

grafik

Dead groups which are not static should not be added as skynet connection during the lua data generation. It should also be restricted to just add Connection Nodes and Power Sources as secondary node to  a Primary node as this is the original root cause of the issue: A campaign designer added an EWR as secondary node to a primary node. As this EWR is non-static it would have been added to the skynet lua data as well which caused the error.

So to fix this issue it will be 2 tasks:
- Prevent the error by skipping dead non-statics
- Restrict which groups can be added as secondary nodes.

### Save game and other files

not required

### PR DESCRIPTION
**Pull request by RndName**
fixes #2537

### CODE REVIEW

**Comment by RndName** [comment]
@DanAlbert you want to review this PR? There was a hidden error in the IADS Network handling when a campaign designer used non valid secondary nodes in the iads_config. Quite a corner case but i added the validation part so that there will be error logs as well as.

**Review by DanAlbert — APPROVED** [review]
> @DanAlbert you want to review this PR?

I did as best as I could, but I haven't grokked the IADS stuff yet. It looks right in general, but I can't spot gameplay issues with IADS since I don't know how any of it works :)

**Comment by DanAlbert** [comment]
@RndName is this ready to merge?

**Comment by RndName** [comment]
> @RndName is this ready to merge?

It is, yes. I was just unsure if you want to review such PRs before i merge them on my own. Was not sure how the new flow is meant to be.

**Pull request merged**
