### PR TITLE
Add checking new version to Help menu

### PR DESCRIPTION
**Pull request by emcek**
It will add new entry to Help menu, to check if there is new release version of DCS Liberation to download. 
* It will check only for official releases (maked green) and not Pre-release (orange one)
* Once there is new version, save dialog will pop-up let user select directory.

This PR needs new requirements (in any version):
* packaging
* requests

### CODE REVIEW

**Comment by emcek** [comment]
I think I can add it is automatic update. I mean unzipping, but I would like discus some stuff:
* where to unzip, in which directory, or simply ask user to select place? Or may be check current directory and unzip new release one dir higher, without asking?
* should be possible to ask user to close Liberation automatically

**Comment by Khopa** [comment]
Hi Emcek, 

Thanks a lot, it's a very good idea and a cool feature ! 😀 

But i can't merge for now it in it's current state on master as it's missing a bit of polishing imo. 

For me, you've done the hardest part, but the UX need a bit of work :
- You should display a message if the version is already up to date. (Otherwise the action feels unresponsive.)
- Also, there should be a progress bar or a least a message to indicate that the download is in progress when it is downloading the zip. The zip appears, but while the download is in progress it is just an empty file, and the app is unresponsive and there is no other feedback. People with bad connection might have to wait for 10+ minutes with the app not responding while the download is in progress. And i know that they will open issues there complaining that the feature does not work 😁 

Also, for me, it triggers an error there : 

```
Traceback (most recent call last):
  File "D:\Work\dcs_liberation\qt_ui\windows\QLiberationWindow.py", line 126, in <lambda>
    help_menu.addAction("Check new version", lambda: self._check_and_download_new_version())
  File "D:\Work\dcs_liberation\qt_ui\windows\QLiberationWindow.py", line 262, in _check_and_download_new_version
    full_zip_path, _ = QFileDialog.getSaveFileName(self, caption='Save File', directory=environ['HOME'],
  File "C:\Python38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
```

As i don't have an 'HOME' environment variable defined. I think you can leave this field empty, so it will default to DCS Liberation current version directory. Maybe retrieve the parent directory for the current running DCS Liberation version. So people can put the new version in the same folder.

Also, not a big issue, but could you make your pull request on develop, through a new feature branch on your repo ?

Thanks a lot, 

Khopa

**Comment by emcek** [comment]
Basically I agree with all comments - I had windows machine to test it.   
I will rebase to develop branch.   
Just one thing progress bar need multi threading code in PySide2 which can be tricky. So I will do first iteration just with message box, and add enhancement with moving progress bar as next PR.

**Comment by Khopa** [comment]
> Just one thing progress bar need multi threading code in PySide2 which can be tricky. So I will do first iteration just with message box, and add enhancement with moving progress bar as next PR.

Yes, that would be great :)

**Comment by DanAlbert** [comment]
Untouched for six months. Going to close, but it can of course be reopened if this gets picked back up.

**Pull request closed without merging**
