### PR TITLE
Creates YAML for HMS Invincible from Razbam South Atlantic map. However won't work as a carrier/control point until PYDCS updated

### PR DESCRIPTION
**Pull request by ColonelAkirNakesh**
Pull requests should be made against the `develop` branch. Any backports
necessary will be handled by the development team.

Pull requests should be focused on one task. Multiple bug fixes should be
multiple PRs. We cannot merge half a PR, and combined PRs are much more
difficult to review. PRs that do not adhere to this will have their review
delayed.

Prefer rebase to merge, and squash commits as needed to preserve a readable
commit history. This project maintains linear history in the develop branch, so
we will either rebase or squash your PR when merging. It is much easier for us
if your branch already has a readable commit history (ensure that your commit
subject lines are clear enough to identify the patch in the git log). An
exception to this is made for large PRs that are likely to require multiple
rounds of review; in that case it's easier if you **don't** do this (GitHub
does not preserve the history of old commits, so we cannot filter a PR for only
new changes if a branch is force pushed) and we will squash it when merging.

New features and bug fixes are usually worth mentioning in the changelog.
Exceptions are fixes for bugs that never shipped (were only present in a canary
build), and changes with no intended user observable behavior, such as a
refactor. If you're comfortable writing the note yourself, add it to
`changelog.md` in the root of the project in the section for the upcoming
release.

### CODE REVIEW

**Comment by DanAlbert** [comment]
> However won't work as a carrier/control point until PYDCS updated

We've updated pydcs many times since the South Atlantic map was released, so that's not it. What's missing? Did I miss a DLC?

**Comment by ColonelAkirNakesh** [comment]
> > However won't work as a carrier/control point until PYDCS updated
> 
> We've updated pydcs many times since the South Atlantic map was released, so that's not it. What's missing? Did I miss a DLC?

Er, sorry! I think it might be this: https://github.com/dcs-liberation/dcs_liberation/blob/1881fecc834e7f311a9377d326ef31d9a9476a6a/game/theater/controlpoint.py around line 30 where the list of ships are, can the Invincible be added to the list?

**Comment by DanAlbert** [comment]
Aha, that'll do it. I'm going to do a bit of cleanup here before merging so that can all be controlled from the yaml files.

**Comment by ColonelAkirNakesh** [comment]
Thanks, Dan, I might create YAMLS for a bunch of naval units that are in PYDCS that don't have YAMLS yet, so noob question: should I do separate pull requests for each one like I did earlier, or is it easier and is there a way to do it all in one request? 

eg I'll add the rest of the South Atlantic ships, but also a few other missing ships here and there

**Comment by DanAlbert** [comment]
> so noob question: should I do separate pull requests for each one like I did earlier, or is it easier and is there a way to do it all in one request?

I never use the web UI so I'm not sure how. Whatever is easiest for you works for me. It's not like these need heavy review or anything like that :)

**Comment by ColonelAkirNakesh** [comment]
> I never use the web UI so I'm not sure how. Whatever is easiest for you works for me. It's not like these need heavy review or anything like that :)

Thanks, Dan, what software do you recommend for someone who is wanting to contribute more? I've been using Windows Notepad up to this point 😱

**Comment by DanAlbert** [comment]
> what software do you recommend for someone who is wanting to contribute more? I've been using Windows Notepad up to this point 😱

Oops, sorry for the delay, I missed this. vscode is probably the best for just editing yaml files.

**Pull request merged**
