### PR TITLE
Appending 'Missions' to the lfs.writedir() path for failover save loc…

### PR DESCRIPTION
**Pull request by adamclmns**
…ation of state.json

Related to Issue opened on behalf of Fox3ms.com - https://github.com/dcs-liberation/dcs_liberation/issues/2381 

This change would remove the need for automation and symlinks to provide access to state.json with dedicated DCS servers. 

PR was opened on advice from "Lion" in the DCS: Liberation Discord  to start further discussion.

### CODE REVIEW

**Comment by DanAlbert** [comment]
I don't object to this, but I'm curious why the environment variable doesn't work? I've never tried running Liberation in this way so sorry if that's a stupid question.

If this is the way to go, I think we should write to the Liberation directory rather than the Missions directory, but otherwise LGTM.

**Comment by adamclmns** [comment]
The Environment Variable requires the desanitzation of "os" which also allows arbitrary code execution. In addition to this, multiple server instances (via -w param to set different write-dirs) saves to the exact same location for all co-located instances when using the environment variable. 

Using lfs.writedir() will narrow the scope from 'host-scope' save directory to 'instance-scope' save directory. We just need to nest it into the "Missions" directory because we only give access to that directory.  We are currently moving the state.json file with scripts for mosts hosts, but many circumstances require manual intervention.

**Comment by DanAlbert** [comment]
You can set environment variables per process though.

Why can't you make `lfs.writedir() .. "/Liberation"` writable?

**Comment by adamclmns** [comment]
> You can set environment variables per process though.
>
That is a possibility, but we don't desanitize 'os' because it's a massive security risk so we can't use environment variables. 

> Why can't you make `lfs.writedir() .. "/Liberation"` writable?

Everything inside of lfs.writedir() is writeable by the exe. I don't understand the question. We only expose the Missions folder to customers.

**Comment by DanAlbert** [comment]
> That is a possibility, but we don't desanitize 'os' because it's a massive security risk so we can't use environment variables.

You can do something like https://gist.github.com/DanAlbert/bdda438b61d36c174b64bf4b5d1bba99 to avoid exposing APIs you deem unsafe, or sandboxing them as needed. You may want to do that regardless if you're security conscious :) Even if you're worried about giving access to secrets that may be in the environment, you can do like I did with the `io` module and restrict the inputs to only certain variables.

(caveat emptor: I have never deployed this somewhere that security matters, but from my limited testing it seems to do the trick)

>> Why can't you make lfs.writedir() .. "/Liberation" writable?
>
> Everything inside of lfs.writedir() is writeable by the exe. I don't understand the question. We only expose the Missions folder to customers.

You said

> We just need to nest it into the "Missions" directory because we only give access to that directory.

Perhaps I misunderstood :)

**Comment by adamclmns** [comment]
The whole reason for the change is that Customers have access to only the Missions folder. They pay for the storage in that directory. When they run Liberation, the state.json pops out somewhere else, that the customer can't access it. There was some customer initiated automation, but that's proven to be very non-user-friendly. If the state.json saved to the Missions directory, then a whole bunch of moving parts become obsolete, and more people can easily enjoy Liberation missions. I've written instructions for the users to update/patch their own liberation installs with the changes reflected in this PR, and they've been using it successfully for a while now. 

> You can do something like https://gist.github.com/DanAlbert/bdda438b61d36c174b64bf4b5d1bba99 

We'll have to test this, as we have customers who run mods like SLMod, Grpc, and others. We will test this further to verify it doesn't have any side effects, and that it mitigates the cyber security concerns. 🍻 

>You said
>> We just need to nest it into the "Missions" directory because we only give access to that directory.

> Perhaps I misunderstood :)

Customers only have access to the "Misisons" directory. The Application can read/write to the Saved Games/DCS.openbeta_server folder. Sorry for the confusion, I wasn't very clear which access I was referring to. 👍

**Comment by DanAlbert** [comment]
My only objection is to writing not-missions to the Missions directory before we're sure there are no other options. This is unlikely to forever be the only piece of data we need to write, and we shouldn't be cluttering the Missions directory with unrelated files. Is the Missions directory really the only possible way for you to do this? I don't understand you can't grant access to other directories within `Saved Games/DCS`. Logs, Mods, Scripts, and Tracks all seem like thing your users would want too.

[Longer term](https://github.com/dcs-liberation/dcs_liberation/issues/104), I assume you'd want to be running the Liberation server on the same machine to further smooth out the workflow, at which point it'd need access to `Saved Games/DCS/Liberation` anyway.

**Comment by DanAlbert** [comment]
I should probably mention that having invalid missions in the `Missions` directory has definitely caused DCS to behave strangely (as in "the mission editor doesn't work at all any more") for me before. I'm hesitant because I don't want to cause problems like that (unlikely though they may be) by writing things that aren't missions to that directory.

**Comment by adamclmns** [comment]
>My only objection is to writing not-missions to the Missions directory before we're sure there are no other options.

Customers only have access to the Missions folder for a lot of reasons that are tedious, and potentially proprietary, but all of these concerns come from a desire for performance, ease of use, and security. We cannot give access to the entire directory due to these concerns. Trust me, we spent the last year working other solutions before reaching out to you guys. This communication has been... challenging.  I'm not understanding the resistance. Customers are already using the Missions folder to save persistence for myriad other missions, and they expected their liberation state.json to work the same, so we've been trying different ways to make that happen.  

> My only objection is to writing not-missions to the Missions directory before we're sure there are no other options. This is unlikely to forever be the only piece of data we need to write, and we shouldn't be cluttering the Missions directory with unrelated files. 

We are aware of the issues that can occur with invalid missions in the mission directory, however this only applies to .miz files that are actively in the server playlist. As stated, we are already directing logs to the directory and customers are using the folder to save persistence for missions. This has caused zero issues, and is not a concern. The users were requesting state.json be moved to the Missions directory just like Foothold saves to by default. If there is a need for Liberation to write something else out from the .miz file, would it not be trivial to adjust the code as needed? 


>https://github.com/dcs-liberation/dcs_liberation/issues/104, I assume you'd want to be running the Liberation server on the same machine to further smooth out the workflow, at which point it'd need access to Saved Games/DCS/Liberation anyway.

This would be a totally different offering, which would come with additional support and maintenance overhead, and honestly seems outside the purview of original issue with the save location. 

Is there a valid concern here, or is this PR okay to accept? If so, I'd love to let our customers know that Liberation missions will now work without any complications.

**Comment by DJ45X** [comment]
Hello! I'm DJ with Fox3, and colleague to adamclmns. 


> My only objection is to writing not-missions to the Missions directory before we're sure there are no other options. This is unlikely to forever be the only piece of data we need to write, and we shouldn't be cluttering the Missions directory with unrelated files. Is the Missions directory really the only possible way for you to do this? I don't understand you can't grant access to other directories within `Saved Games/DCS`. Logs, Mods, Scripts, and Tracks all seem like thing your users would want too.
> 
> [Longer term](https://github.com/dcs-liberation/dcs_liberation/issues/104), I assume you'd want to be running the Liberation server on the same machine to further smooth out the workflow, at which point it'd need access to `Saved Games/DCS/Liberation` anyway.

We totally understand your position with wanting to keep options open for future development with Liberation. With Fox3 being uniquely positioned of being the sole provider of turn-key dedicated DCS game servers, it is pertinent to our mission to maintain safety and security to our customers. We are at the point of surpassing 200+ hosted servers. 


> I should probably mention that having invalid missions in the `Missions` directory has definitely caused DCS to behave strangely (as in "the mission editor doesn't work at all any more") for me before. I'm hesitant because I don't want to cause problems like that (unlikely though they may be) by writing things that aren't missions to that directory.



Our customers rent DCS gameservers, not a VPS. That is the "Managed Solutions" in our name :) We strive to provide the very best solution to the community we share and love. We do not give access to any directory outside the /Missions folder. We do create a junction for /Logs, /Scripts (for those that show aptitude in scripting), /SLMod (for those that know how to set it up) inside the /Missions. 

In the past, one of our customers came up with this `lfs.writedir()` for the [Foothold](https://www.digitalcombatsimulator.com/en/files/3319499/) missions for the very same reason adamclmns is asking for this pr. Within a few days of posting this fix within our discord, the author reached out and said he could make the change official. A vast amount of our customers, including myself, have been successfully running the foothold missions in the very same way on our Fox3 servers without any issues. 

We understand if this is not the direction you wish to go. If there is a way we could work together to provide some kind of resolution we can offer Fox3 customers, I am open to choose that route as well.

**Comment by DanAlbert** [comment]
> for a of reasons that are tedious, and potentially proprietary

Lol, having used more or less that line before, I think I understand. Yeah, we can merge this. I just wanted to be sure it was actually the best option before doing so.

> I'm not understanding the resistance.

Like I said, I've seen DCS do some pretty awful things when if finds things it doesn't expect in the missions directory. I understand that it doesn't matter for your use case if the mission editor works, but this code path might be hit by people that do. Will merge, but if issues are reported related to this we will have to revert. I don't think that's likely, but wanted to give you the heads up.

**Comment by DJ45X** [comment]
> Like I said, I've seen DCS do some pretty awful things when if finds things it doesn't expect in the missions directory. I understand that it doesn't matter for your use case if the mission editor works, but this code path might be hit by people that do. Will merge, but if issues are reported related to this we will have to revert. I don't think that's likely, but wanted to give you the heads up.

If there are any issues reported from this, please inform us and we'd be happy to test and come up with other solutions. Additionally, instead of dropping directly into the root of /Missions, perhaps we could drop the state.json into /Mission/Saves _or_ /Missions/Liberation. That would mitigate issues between the ME and files inside /Missions.

We sincerely appreciate you helping us with this :) cheers!

**Comment by DanAlbert** [comment]
Sounds good. We'll raise any issues on #2381 if they come up, but hopefully they won't :)

**Comment by adamclmns** [comment]
> Sounds good. We'll raise any issues on #2381 if they come up, but hopefully they won't :)

Thank you so much. I will keep an eye out to resolve anything that does come up.

**Pull request merged**
