### PR TITLE
Ah64 add fcr default

### PR DESCRIPTION
**Pull request by zhexu14**
This PR updates the AH64 YAML file to override the DCS default to remove the FCR

### CODE REVIEW

**Comment by Starfire13** [comment]
Would this change mean every Apache gets the FCR? The Ai doesn't use the FCR so it's just for human players.

Perhaps one way to distribute em is to only place em on human player Apaches if there are any in a flight, and if not, only flight lead carries one. AI flight lead carrying one is just purely for looks, of course. That said, I don't know how much of a pain this would be to code.

**Comment by zhexu14** [comment]
> Would this change mean every Apache gets the FCR? The Ai doesn't use the FCR so it's just for human players.
> 
> Perhaps one way to distribute em is to only place em on human player Apaches if there are any in a flight, and if not, only flight lead carries one. AI flight lead carrying one is just purely for looks, of course. That said, I don't know how much of a pain this would be to code.

Yep, all Apaches (AI, Player) would get the FCR. I was thinking that players would be keen to try out the new FCR and it would be annoying to have to remember the uncheck this option every time. AFAICT, it's easy to make either everyone have the FCR or no one have the FCR by default, but harder to default the flight lead to something and everyone else to something else. There is a `player_only` flag but that sits in pydcs and based on the very little I've gathered, that's a DCS thing.

**Comment by DanAlbert** [comment]
Yeah everything you mentioned would be a pain in the ass. This was easy and not wrong.

**Comment by Starfire13** [comment]
Fair enough. Easy is better.

**Pull request merged**
