### PR TITLE
DO NOT SUBMIT: Use print based logging to debug.

### PR DESCRIPTION
**Pull request by DanAlbert**

### CODE REVIEW

**Comment by Raffson** [comment]
I have a feeling you're gonna waste quite some time like I did on this.
Leave this for what it is, I'll fix pydcs to support ANSI description files.
The standard used by ED is UTF8, but some modders encode their description files for custom liveries in another format, making life more difficult.
So far we know encodings can occur in both UTF8 and ANSI, so supporting both makes more sense.
If any other encoding shows up, we can just add it to the list of encodings to try.

**Comment by DanAlbert** [comment]
I haven't had a chance to look at the livery in question yet, but that's my suspicion. There's always a chance that it's actually just an encoding error, but I doubt it in this case.

**Comment by Raffson** [comment]
I pretty much have something that's ready to support ANSI, tested with a custom livery that's ANSI encoded afaik and it's looking good. But despite that I'm also annoyed by the fact that logging isn't propagated through to Liberation.

On a sidenote, have a look at the following commit: https://github.com/Raffson/dcs_liberation/commit/3966e03ea5002be1a93046eec1829b92d7a04e9a
Your change to circular trigger zones broke all campaigns that use quad point triggers, specifically blue zones are the issue.
I decided to implement an approximator for a radius when a quad point is used, and while it's not ideal, I think it's the closest thing to a "coping mechanism" for the changes introduced in pydcs.

**Comment by DanAlbert** [comment]
> I'm also annoyed by the fact that logging isn't propagated through to Liberation.

That's because code that runs at import time cannot be logged. Logging isn't configured until we've reached `main`, by which time the imports have already been done.

> Your change to circular trigger zones broke all campaigns that use quad point triggers, specifically blue zones are the issue.

Those are campaign bugs: https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-campaigns#map-objects

**Comment by Raffson** [comment]
> Those are campaign bugs: https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-campaigns#map-objects

Interesting, thanks for pointing that out 👍

Either way, supporting different encodings will solve the problem, but life would obviously be easier if we could at least log which file is failing, thus being able to determine what encoding we're missing to fix future problems.

**Comment by DanAlbert** [comment]
> life would obviously be easier if we could at least log which file is failing

Agreed. To do that the liveries API in pydcs probably needs to change. Loading liveries at import time makes this impossible (or at least very difficult and error prone).

**Comment by Raffson** [comment]
> Loading liveries at import time makes this impossible (or at least very difficult and error prone).

I know, because during my tests with Starfire that's exactly the wall I ran into. The livery scanner can only be delayed as long as the types that use it get delayed, but that's a tough nut to crack in Liberation.

Alternatively I can think of a (possible) solution which introduces more design changes in pydcs, more specifically I have the following in mind. The idea is to replace the `Liveries` class variable of a `FlyingType` with a ~~property~~ classmethod. This might delay initialization of the scanner until the first time "an aircraft's liveries is queried".

~~Tbh, I think it's a long shot, but~~ definitely worth trying so I'll see what I can do about it after I'm done with extra encoding support, which should be any minute now.

**Comment by Raffson** [comment]
That turned out to be easier than I expected.
From what I can tell, the initialization is delayed until the "new game" button is clicked.
Double checked in an actual release version and the logging shows up so I guess it's a reasonable fix.

**Pull request closed without merging**
