### PR TITLE
Remove AI F-15E from Starfire's campaigns

### PR DESCRIPTION
**Pull request by Starfire13**
Now that the F-15E Suite 4+ has JDAMs and the bug preventing AI from using LGBs has been fixed, I have removed the AI-only F-15Es from my campaigns. Also minor tweaks to a couple of squadron types/sizes based on play-testing results.

### CODE REVIEW

**Comment by DanAlbert** [comment]
Given https://github.com/dcs-liberation/dcs_liberation/pull/3259, do you still want to merge this?

**Comment by Starfire13** [comment]
Yeah, it's fine to merge. The AI do well enough with JDAMs.

**Comment by Starfire13** [comment]
The vegas nerve yaml that you merged earlier is actually newer than the one in this pr though. Will you be able to prevent the one in here from overwriting when merging? If not, I can edit the PR when I get home tonight.

**Comment by DanAlbert** [comment]
Ah, the other PR included this update. Looks like it merged correctly (that is, this PR no longer has a change to that campaign, because the change the was here is already merged).

**Pull request merged**
