### PR TITLE
Updated Weapon Damage Updates script with cluster weapons effects

### LINKED ISSUE #2232: Update Wheelyjoe's Weapons Damage Mod
* Mod name: Wheelyjoe's Weapons Damage Mod (aka "Splash Damage" mod)
* Mod URL:  https://github.com/wheelyjoe/DCS-Scripts
* Update or new mod? Update

This is being submitted at Ghosti's request, and based on some testing Ghosti and I have been conducting on adding cluster munitions to Wheelyjoe's Weapons Damage Mod (what is popularly referred to as the splash damage mod). Cluster munitions that will be added are the AGM-154A, CBU-87, and CBU-103.

Based on preliminary testing, it appears that a explTable setting of 100 and a clusterWeaps setting of 145 is acceptable. However, the area of effect should be changed from a square to a circle, and the diameter boosted to 150m. Note that all these values are ballpark placeholders and at least some of them (if not all) may have to be tweaked (in particular, explTable).

These changes can either be added to the current plugin, either on or off by default, and perhaps toggleable via the LUA plugin options panel.

I also suggest that the plugin be named the same way as Wheelyjoe's actual mod, as it is no longer called the splash damage mod, and the name gives a false impression of what it actually does.

### PR DESCRIPTION
**Pull request by MetalStormGhost**
Updated (and renamed in Liberation) Wheelyjoe's Weapon Damage Updates script with cluster weapons effects. If enabled, now generates extra explosions near BLU-97/B hits to simulate the missing submunitions which are omitted by ED due to performance reasons. This is an attempt at making the A-model JSOW (and the CBU-87/CBU-103 which use the same submunition) more useful against groups of soft targets.

The cluster munition damage updates option can be turned on or off in the plugin settings.

Resolves #2232

### CODE REVIEW

**Comment by DanAlbert** [comment]
I don't fully understand. Does this have modifications that are not present upstream, or are the cluster munition changes just a feature from the update?

**Comment by MetalStormGhost** [comment]
> I don't fully understand. Does this have modifications that are not present upstream, or are the cluster munition changes just a feature from the update?

They are my own modifications to the original script, and the added features of making the cluster effects optional in the Plugin options in Liberation.

The motivation for this change is as follows:
https://discord.com/channels/595702951800995872/782358861117259776/972840138507964476
Starfire — 08/05/2022
The JSOW-A is just basically worthless.
ED reduced the number of bomblets in the JSOW-A for performance reasons.

**Comment by DanAlbert** [comment]
Have you tried upstreaming those changes? Downstream modifications carry a significant maintenance cost.

**Comment by MetalStormGhost** [comment]
> Have you tried upstreaming those changes? Downstream modifications carry a significant maintenance cost.

I sent a message to Wheelyjoe on Discord for upstreaming.

**Comment by DanAlbert** [comment]
Just send them the PR? Closing this because we'll just take the real update when it's ready.

**Pull request closed without merging**
