### PR TITLE
F-104 mod support version 2.7.11.222.01

### PR DESCRIPTION
**Pull request by MetalStormGhost**
Updated the VSN F-104 mod support to version 2.7.11.222.01. This version adds the F-104C fighter bomber variant, so added the icon, loadouts and aircraft yaml for it.

### CODE REVIEW

**Comment by DanAlbert** [comment]
We're closing stale PRs. If this is still needed, please update and reopen.

**Comment by MetalStormGhost** [comment]
Changelog conflict resolved. 2.7.11.222.01 is still the latest release of the F-104 mod.

**Comment by Raffson** [comment]
This is going to conflict with the latest pydcs update #2347. I recommend dropping the pydcs extension file because I got one incorporated with the update. It's a necessity because otherwise mods will throw exceptions on mission generation.

**Comment by MetalStormGhost** [comment]
> This is going to conflict with the latest pydcs update #2347. I recommend dropping the pydcs extension file because I got one incorporated with the update. It's a necessity because otherwise mods will throw exceptions on mission generation.

I converted this to a draft. I'll wait for #2347 to be merged and see what do I need to do to bring this up to date after that. Thanks for the heads up @Raffson !

**Comment by Raffson** [comment]
> I converted this to a draft. I'll wait for #2347 to be merged and see what do I need to do to bring this up to date after that. Thanks for the heads up @Raffson !

Probably better than my original suggestion to drop it, cause now that I think about it I had some trouble with the 104's weapons. Definitely something to keep a close eye on when merging.

**Pull request closed without merging**
