### PR TITLE
[WIP] Rerun planner with UI Button and allow to limit assigned aircrafts

### PR DESCRIPTION
**Pull request by RndName**
This one is a WIP and needs more work.

This PR will allow the user to re-run the TheaterCommander to fill up unassigned aircrafts or recreate missing packages. This PR also will allow the user to setup a limit of aircrafts which should be assigned for tasking so that users optimize the mission on theire own to regain some performance if many aircrafts are available.

This addresses #799 and #643

TODOs:

- [ ] TOT (Later planned things dont have a good TOT assigned)
- [ ] OCA (Differentiate between runway and aircraft)
- [ ] Garrisons
- [ ] NavalGroundObjects
- [ ] Stances will be overwritten by CaptureBase & DefendBase
- [ ] Assignable_aircraft not implemented yet for the Commander
- [ ] UI Implemention for Aircraft Count and Button are just draft and will not update correctly

### CODE REVIEW

**Comment by RndName** [comment]
@DanAlbert hey i am currently working on an enhancement to rerun the Package Planning via a button in the UI so that missing tasks or unassigned aircrafts can be taken in account of the Planner again (for example if you manually added all the packages and now only want to fill with the rest of possible things). Also i want to restrict the maximum amount of Aircrafts assigned to missions to have another performance setting. 

My current approach to detect if the Theatercommander has to plan the specific mission is to change how the TheaterState will be generated. I adopted the State that it checks if already planned packages from the coalition.ato exists and therefore dont add the MissionTargets to the lists (example: barcaps_needed -> I reduce the amount of needed packages for any barcap flight for the Mission Target the objectivefinder finds in the coalition.ato). Same goes for any other flight type which has a list in the state). I adopted the State for quite alot of flight types already but im not finished yet.

I would be glad if you may have some time to look over the general concept i implemented already just to make sure i am going in the right direction inbefore i continue to finish this one :slight_smile: I am not 100% confident yet with the new HTN you implemented so i think its better to ask you inbefore i spent some time on it and you may have a better approach to achieve this one :wink:

Thanks!

**Comment by DanAlbert** [comment]
Finally came up with an approach I like:

Instead of making objective finder responsible for pruning the missions that are already planned, add an `apply_ato` method to `TheaterState` that walks every flight in the ATO and applies its effects to the `TheaterState`. To avoid behavior mismatches, change the guts of `apply_mission_effects` to call through to a new `TheaterState.apply_task_to_target(self, task: FlightType, target: MissionTarget, allow_ineffective: bool = False)`. The last argument would be used when called by `apply_ato` since that may include player missions that do things our `TheaterState` doesn't model like multiple DEAD packages against a single target. We'd normally want that to be an error, but the error should be ignored when it's from the player.

Wdyt?

**Comment by RndName** [comment]
> 
> 
> Finally came up with an approach I like:
> 
> Instead of making objective finder responsible for pruning the missions that are already planned, add an `apply_ato` method to `TheaterState` that walks every flight in the ATO and applies its effects to the `TheaterState`. To avoid behavior mismatches, change the guts of `apply_mission_effects` to call through to a new `TheaterState.apply_task_to_target(self, task: FlightType, target: MissionTarget, allow_ineffective: bool = False)`. The last argument would be used when called by `apply_ato` since that may include player missions that do things our `TheaterState` doesn't model like multiple DEAD packages against a single target. We'd normally want that to be an error, but the error should be ignored when it's from the player.
> 
> Wdyt?

Thanks for your ideas!! I will have a closer look when i have more time to focus on it with 100% dedication :) For the time beeing i will close the PR as it was just to check the general concept :)

**Comment by DanAlbert** [comment]
Sounds good. Agreed with the general concept 👍

**Pull request closed without merging**
