### PR TITLE
waypointbuilder: low altitude waypoints for helos

### PR DESCRIPTION
**Pull request by benedikt-wegmann**
This addition to the `waypointbuilder` makes helo waypoints low AGL altitudes for more realistic helo operations.

### CODE REVIEW

**Comment by DanAlbert** [comment]
Can the AI fly this pattern without getting themselves killed? IME the AI is quite bad at flying AGL waypoints, which I assume was the reason for the higher altitude.

**Comment by benedikt-wegmann** [comment]
I have set helos in mission editor low and it was fine (although not always graceful). If you have concerns, let this MR stand for a while and let me continue my current campaign and observe more.
Primary goal was to have the helos operating somewhat in the vicinity of SAMs without getting picked off every time, or even make them able to fly DEAD (which should be natural for a Ka-50 or AH-64).
I'll report back! :+1:

**Comment by DanAlbert** [comment]
Yeah, wholly agreed on the direction, and the code is fine :) If all seems to be working for well for you after a couple days lmk and we'll merge.

**Comment by DanAlbert** [comment]
On second thought this is just going to preview anyway so I'll merge now and we can get extra testing. Can always revert if people find issues.

**Comment by benedikt-wegmann** [comment]
@DanAlbert Yeah, revert or tuning the numbers is always a possibility. Motivation simply was to make helos more viable. I'll keep an eye out on how they perform during my next missions. :beers:

**Pull request merged**
