### PR TITLE
Generate kneeboards for player flights.

### PR DESCRIPTION
**Pull request by DanAlbert**
Example of kneeboard for an F-16

I've added two new dependencies: pillow, for generating the kneeboard images; and tabulate, for creating the tables in the kneeboards.

For the kneeboard layout, I also investigated using jinja2 so we could use HTML templates which would have been quite a bit nicer to work with, but converting the HTML output to an image (which DCS requires) required too many external dependencies for users. Python's imgkit required wkhtmltoimage, which would be a pain for users to install, or a dependency on a web service. Neither seemed a great choice, so ugly plain text it is. If we want to make it prettier later we could always create a background image that we can fill in to make it look more like a proper form.

Wasn't sure what fonts could be relied on for every machine, so I included the monospaced font in the package. It's freely licensed, and the license is packaged in the release. We still depend on arial.ttf being available on the host. I can either package another font, switch everything to inconsolata, or maybe find a fallback option in pillow.

Carrier ATC/TCN/ICLS isn't implemented yet, and I've only added the information for a single airfield. Will follow up to flesh that out.

### CODE REVIEW

**Comment by emcek** [comment]
I see you use `dataclass` decorator, which was introduce in Python 3.7, but looks like DCS Liberation should be [Python 3.6+](https://github.com/Khopa/dcs_liberation/wiki/Developer's-Guide#required-tools) compatible.

**Comment by DanAlbert** [comment]
Hadn't noticed that, thanks for the heads up. @Khopa any reason to continue supporting 3.6? aiui the release packages its own python.

**Comment by Khopa** [comment]
> Hadn't noticed that, thanks for the heads up. @Khopa any reason to continue supporting 3.6? aiui the release packages its own python.

No, i'm also using Python 3.8 now. I think we should all go to 3.8, i'll update dev guide.

**Comment by DanAlbert** [comment]
Glad to hear it. Let me know if any changes need to be made here. Excited to get this merged :)

**Comment by DanAlbert** [comment]
[Generate custom kneeboard](https://trello.com/c/mJ78MHTb/47-generate-custom-kneeboard)

**Comment by Khopa** [comment]
> Glad to hear it. Let me know if any changes need to be made here. Excited to get this merged :)

Me as well, i'll try to review and merge this as soon as possible :)

**Comment by Khopa** [comment]
Great, it's working fine for me :)
So i'm merging.

Just a quick note, i already had a few units conversions functions in game/utils.py. I see you added a gen/units.py file for the same purpose. Maybe we should refactor unit conversions in a new dedicated module.

**Pull request merged**
