### PR TITLE
Update tasks for Uh60L

### PR DESCRIPTION
**Pull request by KingSharkoon**
Adding tasks like CAS and Strike to the UH60L so it can be used for transport and CTLD on Frontlines and Target Areas

### CODE REVIEW

**Comment by Starfire13** [comment]
You want to do fighter sweep and escort with a UH-60?

**Comment by KingSharkoon** [comment]
> You want to do fighter sweep and escort with a UH-60?

No - but I want an option to assign the uh60l mod to those tasks to create the waypoints etc.

**Comment by DanAlbert** [comment]
Use custom waypoints for that. Adding to these lists means the AI will consider it for those missions.

**Comment by KingSharkoon** [comment]
> Use custom waypoints for that. Adding to these lists means the AI will consider it for those missions.

Not possible because the only task for the UH60 is Transport … with that it is useless at the moment even if it is implemented - with Cas and Strike added, you can select it to transport troops and crates to the desired target areas. If you have a better option I am of course open for it

**Comment by DanAlbert** [comment]
> Adding to these lists means the AI will consider it for those missions.

I'd misunderstood initially. These aren't those lists.

> If you have a better option I am of course open for it

Add planning for transport missions? You're not actually trying to plan CAS, Strike, Sweep, etc missions. This PR just enables abusing those mission types to plan transport flights (and I'm not actually sure it does that correctly; the build-in DCS task types are generally useless in Liberation because they don't map to Liberation mission types).

**Comment by kevotosmart** [comment]
Ugh it’s not useless I can generate missions all day. And I attest adding it to anything besides transport will cause issues. 

Buy ground units, set up to transport them to another airbase or fob , set yourself as a player on the generated uh-60l transport flight. 

Maybe a better request could be to allow to be able to create transport missions in general.

**Comment by DanAlbert** [comment]
That's what I suggested.

**Comment by RndName** [comment]
PR got stale and as suggested the better solution is to allow Transfer missions to be created by the user (#2163) instead of adding more tasks which are not suitable

**Pull request closed without merging**
