### PR TITLE
FOBs still being generated as TGOs...

### LINKED ISSUE #2139: ValueError: Unhandled building category: fob in log on using cheat to capture a FOB
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2048799345

### Description

An error is generated in the log (with no popup) when a FOB is cheat-captured. This error does not prevent the FOB from being cheat captured, but should probably be looked at in case it breaks anything else behind the scenes.

Traceback (most recent call last):
  File "uvicorn\protocols\http\httptools_impl.py", line 367, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 212, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 61, in app
  File "fastapi\routing.py", line 226, in app
  File "fastapi\routing.py", line 161, in run_endpoint_function
  File "starlette\concurrency.py", line 39, in run_in_threadpool
  File "anyio\to_thread.py", line 28, in run_sync
  File "anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 754, in run
  File "game\server\tgos\routes.py", line 19, in get_tgo
  File "game\server\tgos\models.py", line 52, in for_tgo
  File "game\sidc.py", line 346, in sidc
  File "game\theater\theatergroundobject.py", line 323, in symbol_set_and_entity
ValueError: Unhandled building category: fob
2022-03-29 18:24:41,670 :: root :: ERROR :: Uncaught (in promise) Error: Request failed with status code 500

### Save game and other files

[Cheat Capture Test File #3733.zip](https://github.com/dcs-liberation/dcs_liberation/files/8369056/Cheat.Capture.Test.File.3733.zip)

### PR DESCRIPTION
**Pull request by Raffson**
Fixes #2139

~~FOB was forgotten during the refactor (commit 0238376...)~~

### CODE REVIEW

**Comment by DanAlbert** [comment]
Because FOBs are CPs, not TGOs. If we're still generating FOB TGOs we should probably stop doing that.

**Comment by Raffson** [comment]
Right, in that case I'll revert the changes and figure out where FOB TGOs are still being generated...

**Comment by Raffson** [comment]
Could `GameDB` be the culprit? It looks like all ground objects, including CPs, are being stored as TGOs...

Though I seem to be missing a connection to a capture event since the problem manifests during captures only AFAIK.

**Comment by Raffson** [comment]
Also, FOB's seem to be referencing themselves in their `connected_objectives` which I assume is the cause of the problem, so I'm kinda looking for a needle in a haystack now...

**Comment by Raffson** [comment]
Noticed that carriers are somewhat in the same situation, they're also both CPs and TGOs...

**Comment by DanAlbert** [comment]
> Noticed that carriers are somewhat in the same situation, they're also both CPs and TGOs...

I wasn't quite clear earlier. For FOB/FARP/CV/LHA CPs, there is a TGO associated with the base. That's sort of an implementation quirk that's used for spawning the units; they otherwise do not behave like other TGOs (they aren't displayed on the map as a TGO and are not targetable).

What I should have said is that we should stop generating non-CP FOBs.

So yes, we should be generating all of these things as TGOs, but they should only ever be as the implementation of a CP, and I don't think this code is relevant for that. If we're generating any FOBs that are _not_ CPs, that's the thing we should probably remove. Based on the callstack in the bug, that is the problem, because the SIDC creation is coming from a place that is guarded against `tgo.is_control_point`: https://github.com/dcs-liberation/dcs_liberation/blob/30bdcfac29e083d85ecb8240e79b4483f29244d8/game/server/tgos/models.py#L31-L56

**Comment by DanAlbert** [comment]
I think https://github.com/dcs-liberation/dcs_liberation/blob/develop/resources/layouts/buildings/fob1.yaml is the cause, but it only has the FOB task, not StrikeTarget...

Maybe the problem is from the other end. The FOB TGO that's causing the issue is the CP itself, but for some reason `is_control_point` is `False`?

**Comment by DanAlbert** [comment]
A quick audit makes it look like that's not the issue either. I think inspecting with the debugger is probably the best way to get answers.

**Comment by Raffson** [comment]
> I wasn't quite clear earlier. For FOB/FARP/CV/LHA CPs, there is a TGO associated with the base. That's sort of an implementation quirk that's used for spawning the units; they otherwise do not behave like other TGOs (they aren't displayed on the map as a TGO and are not targetable).

I think that's the main reason, a TGO is still made to represent the FOB in-game, though we could get rid of the error by handling a FOB just like an airbase, cause essentially what the `GroundObjectGenerator` does for a FOB is add a building to the `connected_objectives` and it's exactly that addition that causes the problems. Upon capture all TGOs (which is looping over `connected_objectives`) are pushed into the eventstream, and so the front-end tries to query the FOB as a TGO, which in turn tries to call `sidc()` but unlike a CV and LHA who have their own overriding implementations for `symbol_set_and_entity()`, a FOB is a `BuildingGroundObject` so that explains the issue.

Now that makes me wonder, maybe we could just prevent the TGO update for the FOB since it ought to have updated through `updated_control_points`. I'll give it a try, let you know what the results are...

**Comment by Raffson** [comment]
@DanAlbert So I just tried my last idea, seems to work and I don't think this breaks anything, in fact should be a very slight improvement in performance...

**Pull request merged**
